### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by simon-p-r** [mkg20001/pkg-natives#3]
Hi

I tried using your module however I am getting above error.

Thanks

**Comment by mkg20001** [comment]
Can you give me more information about your project? Which module is the failing DDL from? What version of node are you using?

**Comment by simon-p-r** [comment]
I created a simple script that uses this native module https://github.com/simon-p-r/napi-crypto, I will create a repo as I have tried more than one tool to package up a node app with native dependency and none work.

**Comment by mkg20001** [comment]
Ok. I just need a small script to test the behaviour. Does simply requiring the module cause the error?

**Comment by mkg20001** [comment]
```
Error: Could not locate the bindings file. Tried:
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/build/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/build/Debug/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/build/Release/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/out/Debug/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/Debug/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/out/Release/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/Release/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/build/default/napi-crypto.node
 → /home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/compiled/8.9.3/linux/x64/napi-crypto.node
    at bindings (/home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/node_modules/napi-crypto/lib/index.js:3:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/maciej/Projekte/Unsortiert/pkg-natives/test/testpkg/index.js:5:20)
```
Is what I get when I require the module. It would be nice if it would at least run 'node-gyp rebuild' on postinstall

**Comment by mkg20001** [comment]
I think the reason why the DLL fails to load is because it is compiled differently than all other node C/C++ addons. I try to compile it with node-gyp.
(Edit: In cmake some source files are required (`PRIVATE ${CMAKE_SOURCE_DIR}/node_modules/node-addon-api`) and they are most likely not statically linked so the DLL does not find them. Also, please use the official way to create and build C/C++ addons if you want to avoid such errors)

**Comment by simon-p-r** [comment]
Module works fine before trying to package it up so it has nothing to do with cmake toolchain.

**Comment by mkg20001** [comment]
Have you read the edit?

**Comment by simon-p-r** [comment]
Sorry, I don't follow.
